# Check https://rust-lang.github.io/rustfmt for more options

reorder_imports = true
imports_granularity = "Module"
group_imports = "StdExternalCrate"

max_width = 70
use_small_heuristics = "max"

fn_single_line = true
merge_imports = true
reorder_impl_items = true
tab_spaces = 2